export const LOAD_ITEMS_REQUEST = "LOAD_ITEMS_REQUEST";
export const LOAD_ITEMS_SUCCESS = "LOAD_ITEMS_SUCCESS";
export const LOAD_ITEMS_FAIL = "LOAD_ITEMS_FAIL";

export const CHANGE_CATEGORY = "CHANGE_CATEGORY";

export const LOAD_CATEGORIES_REQUEST = "LOAD_CATEGORIES_REQUEST";
export const LOAD_CATEGORIES_SUCCESS = "LOAD_CATEGORIES_SUCCESS";
export const LOAD_CATEGORIES_FAIL = "LOAD_CATEGORIES_FAIL";

export const ADD_TO_CART_REQUEST = "ADD_TO_CART_REQUEST";

export const REMOVE_FROM_CART_REQUEST = "REMOVE_FROM_CART_REQUEST";
